package rules.discounts;
import com.iphrends.drools.models.Order;

rule "HDFC" salience 1
    activation-group "ag1"
    when
        orderObject : Order(cardType=="HDFC" && price>10000);
    then
        orderObject.setDiscount(9);
        //update(orderObject);
end;

rule "HDFC2" salience 2
    activation-group "ag1"
    when
        orderObject : Order(cardType=="HDFC" && price>10000);
    then
        orderObject.setDiscount(10);
        update(orderObject);
end;

rule "ICICI"
    when
        orderObject : Order(cardType=="ICICI" && price>15000);
    then
        orderObject.setDiscount(8);
        update(orderObject);
end;

rule "DBS"
    when
        orderObject : Order(cardType=="DBS" && price>15000);
    then
        orderObject.setDiscount(15);
        update(orderObject);
end;